version: "3.5"

# Based of Django+Docker Setup Reference: https://docs.docker.com/samples/django/
services:
    db:
        container_name: article_db
        image: postgres
        volumes:
            - ./postgres/db:/var/lib/postgresql/
        env_file: ./conf/db/.env
            
    article_api:
        container_name: article_api
        image: article_api
        build: 
            context: .
            dockerfile: ./conf/app/Dockerfile
            args:
                - ENV=dev
        entrypoint: python ./app/manage.py runserver 0.0.0.0:8000
        env_file: ./conf/app/.env
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

                